name: Generate and Upload BOM to Dependency-Track

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install cyclonedx-bom

    - name: Generate CycloneDX BOM
      run: |
        cyclonedx-py -e -o bom.xml

    - name: Upload BOM to Dependency-Track
      run: |
        curl -X "PUT" "http://dependency-track-server/api/v1/bom" \
             -H "X-Api-Key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}" \
             -H "Content-Type: multipart/form-data" \
             -F "project=${{ secrets.DEPENDENCY_TRACK_PROJECT_UUID }}" \
             -F "bom=@bom.xml"
